# This file is part of the Kreta package.
#
# (c) Beñat Espiña <benatespina@gmail.com>
# (c) Gorka Laucirica <gorka.lauzirika@gmail.com>
#
# For the full copyright and license information, please view the LICENSE
# file that was distributed with this source code.

parameters:
    kreta_simple_api_doc.extractor.api_doc_extractor.class: Kreta\SimpleApiDocBundle\Extractor\ApiDocExtractor
    kreta_simple_api_doc.parser.validation_parser.class: Kreta\SimpleApiDocBundle\Parser\ValidationParser

services:
    kreta_simple_api_doc.extractor.api_doc_extractor:
        class: %kreta_simple_api_doc.extractor.api_doc_extractor.class%
        arguments:
            - @service_container
            - @router.default
            - @annotation_reader
            - @nelmio_api_doc.doc_comment_extractor
            - @nelmio_api_doc.controller_name_parser
            - []
            - []
            - @kreta_simple_api_doc.parser.validation_parser
    kreta_simple_api_doc.parser.validation_parser:
        class: %kreta_simple_api_doc.parser.validation_parser.class%
        arguments:
            - @validator.mapping.class_metadata_factory
            - @validator
